// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	Path      *string `json:"path,omitempty"`
	ProxyPass *string `json:"proxyPass,omitempty"`
}

type LocationInput struct {
	Path      *string `json:"path,omitempty"`
	ProxyPass *string `json:"proxyPass,omitempty"`
}

type Mutation struct {
}

type NginxConfig struct {
	ID           string      `json:"id"`
	ServerName   *string     `json:"serverName,omitempty"`
	ListenPort   *int        `json:"listenPort,omitempty"`
	ServerTokens *bool       `json:"serverTokens,omitempty"`
	Locations    []*Location `json:"locations,omitempty"`
}

func (NginxConfig) IsEntity() {}

type NginxConfigInput struct {
	ServerName   *string          `json:"serverName,omitempty"`
	ListenPort   *int             `json:"listenPort,omitempty"`
	ServerTokens *bool            `json:"serverTokens,omitempty"`
	Locations    []*LocationInput `json:"locations,omitempty"`
}

type Query struct {
}
