package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/nebucloud/nginx-service/internal/graphql/generated"
	"github.com/nebucloud/nginx-service/internal/graphql/model"
)

// Empty is the resolver for the _empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// UpdateNginxConfig is the resolver for the updateNginxConfig field.
func (r *mutationResolver) UpdateNginxConfig(ctx context.Context, id string, config model.NginxConfigInput) (*model.NginxConfig, error) {
	panic(fmt.Errorf("not implemented: UpdateNginxConfig - updateNginxConfig"))
}

// AddNginxConfig is the resolver for the addNginxConfig field.
func (r *mutationResolver) AddNginxConfig(ctx context.Context, config model.NginxConfigInput) (*model.NginxConfig, error) {
	panic(fmt.Errorf("not implemented: AddNginxConfig - addNginxConfig"))
}

// DeleteNginxConfig is the resolver for the deleteNginxConfig field.
func (r *mutationResolver) DeleteNginxConfig(ctx context.Context, id string) (*string, error) {
	panic(fmt.Errorf("not implemented: DeleteNginxConfig - deleteNginxConfig"))
}

// NginxConfig is the resolver for the nginxConfig field.
func (r *queryResolver) NginxConfig(ctx context.Context, id string) (*model.NginxConfig, error) {
	panic(fmt.Errorf("not implemented: NginxConfig - nginxConfig"))
}

// ListNginxConfigs is the resolver for the listNginxConfigs field.
func (r *queryResolver) ListNginxConfigs(ctx context.Context) ([]*model.NginxConfig, error) {
	panic(fmt.Errorf("not implemented: ListNginxConfigs - listNginxConfigs"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
